name: L1 Quick Start
run-name: ${{ github.actor }} L1

on: [push, workflow_dispatch]

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "trigger=${{ github.event_name }} branch=${{ github.ref }}"
      - run: uname -a